theme: jekyll-theme-minimal
title: Felipe's homepage
description: Bookmark this to keep an eye on my project updates!
            Contact Me - frodriguez@my365.bellevue.edu
            Linkdin - www.linkedin.com/in/felipe-rodriguez-4427321bb
