---
title: "Week 11 & 12"
author: "Felipe Rodriguez"
date: "`r Sys.Date()`"
output: pdf_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen=999)
```

```{r}
setwd("/Users/feliperodriguez/OneDrive - Bellevue University/DSC 640 Data Prep and Vis/Week 11&12")
data <- read.csv("education.csv", )
```


```{r}
# Histogram
dropout <- data$dropout_rate
hist(dropout,
     main = "Historgram R")

```

```{r}
# Box Plot R
reading <- data$reading
math <- data$math
writing <- data$writing

boxplot(reading, math, writing,
main = "Box Plot R",
names = c("Reading", "Writing", "Math"),
las = 2,
col = c("orange","red", "blue"),
border = "brown",
horizontal = TRUE,
notch = TRUE
)
```

```{r}
# Bullet Plot
library(plotly)
library(ggplot2)

p <- data %>% 
  ggplot(aes(x = dropout_rate, y = state)) +
  geom_col(aes(x = pupil_staff_ratio), fill = "grey") +
  geom_col(width = 0.5, fill = "black") + 
  ggtitle("Bullet Chart R")

ggplotly(p)
```

```{r}
library(fmsb)
data <- read.csv("education.csv", header=TRUE, row.names="state")

# Assign Min and Max to all columns
max_min <- data.frame(
  reading = c(620, 0), math = c(620, 0), writing = c(620, 0),
  percent_graduates_sat = c(100, 0), pupil_staff_ratio = c(15, 0), dropout_rate = c(10, 0)
)
rownames(max_min) <- c("Max", "Min")

# Add max_min to data
df <- rbind(max_min, data)
# Create dataframe for variable
Nebraska <- df[c("Max", "Min", "Nebraska"), ]
# Create radar chart
radarchart(Nebraska, title = "Radar Chart R")
```